sudo: false
language: haxe
haxe:
  - "3.2.1"
addons:
  apt:
    packages:
    - libclosure-compiler-java
before_install:
  - nvm install v4.6.2
script:
  - (cd haxe; haxe -cp src -cp test -main RunTests -resource ../snapshots/snapshot-rev4.json@snapshot-rev4 --interp)
  - make bin/husl.min.js
  - (cd javascript; npm test)